---
title: "native_food_preferences"
author: "Kevin Havis"
format: html
---

```{r}
source('load_data.R')
```


 What cuisines do women prefer compared to men?

1. Calculate overall mean rating per country
2. Calculate mean per country by gender
3. Compare differences in two means

```{r}
# Convert to long form data
long_data <- data |> 
  pivot_longer(cols = algeria:ireland, names_to = "country", values_to = "rating")
```

```{r}
# Calculate overall rating means per country
long_data |> 
  drop_na(gender) |> 
  group_by(country) |> 
  summarize(mean_rtg = mean(rating, na.rm = TRUE))
```
```{r}
ggplot(long_data, aes(x=rating)) +
  geom_histogram() +
  facet_wrap(~gender)
```


```{r}
# Calculate overall rating means per country for men
men_rtg <- long_data |> 
  filter(gender == "Male") |> 
  group_by(country) |> 
  summarize(mean_rtg = mean(rating, na.rm = TRUE))
```

```{r}
# Calculate overall rating means per country for women
women_rtg <- long_data |> 
  filter(gender == "Female") |> 
  group_by(country) |> 
  summarize(mean_rtg = mean(rating, na.rm = TRUE))
```

```{r}
# Plot mens ratings vs women's ratings

ggplot() +
  geom_histogram(data = men_rtg, aes(x=mean_rtg), fill = 'blue', alpha = 0.8) +
  geom_histogram(data = women_rtg, aes(x=mean_rtg), fill ='red', alpha = 0.8)

```
```{r}
anova_results <- aov(rating ~ gender + country, data = long_data)

summary(anova_results)
```

```{r}
plot(anova_results, which = 2)
```



